# Generated by Django 3.2.13 on 2022-06-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I4G008040APG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
